/*
 * nRF905.c
 *
 *  Created on: Oct 17, 2017
 *      Author: zulolo
 *      Description: Use wiringPi ISR and SPI feature to control nRF905
 */
//#include <stdint.h>
#include <sys/time.h>       /* for setitimer */
#include <signal.h>     /* for signal */
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include "wiringPi.h"
#include "wiringPiSPI.h"
#include "system.h"
#include "nRF905.h"

#define NRF905_TX_EN_PIN				0
#define NRF905_TRX_CE_PIN				2
#define NRF905_PWR_UP_PIN				3
#define NRF905_DR_PIN					4

#define US_PER_SECONDE					1000000
#define NRF905_TX_ADDR_LEN				4
#define NRF905_RX_ADDR_LEN				4
#define NRF905_RX_PAYLOAD_LEN			32
#define NRF905_TX_PAYLOAD_LEN			NRF905_RX_PAYLOAD_LEN

typedef enum _nRF905Boolean {
	NRF905_FALSE = 0,
	NRF905_TRUE = !NRF905_FALSE
}nRF905Boolean_t;

typedef enum _RF_CMD {
	RF_READ_SENSOR_VALUE = 0,
	RF_WRITE_MOTOR_PAR,
	RF_CMD_FAILED
}RF_Command_t;

//typedef enum _nRF905CommType {
//	NRF905_COMM_TYPE_RX_PKG = 0,
//	NRF905_COMM_TYPE_TX_PKG
//}nRF905CommType_t;
//
//typedef struct _CommTask {
//	nRF905CommType_t tCommType;
//	uint8_t unCommByteNum;
//	uint8_t* pTX_Frame;
//	uint8_t* pRX_Frame;
//}nRF905CommTask_t;

/* Here is how the RF works:
 * UP keeps monitoring if there is any valid frame available (CD, AM, DR should be all SET) on certain channel for 300ms.
 * If yes, receive frame and continuously monitoring on this channel. If no, hop to next channel according to the hopping table.
 *
 * Down keeps transmitting frames every 100ms. If transmitting failed, (can not get valid response) down start hopping procedure.
 * Hopping procedure is to trying burst transmitting ACK frame continuously.
 * If transmitting failed, jump to next channel according to table and start to transmit again.
 * The TX&RX address is generated by some algorithm and is set at start up or during hopping
 *
 */
#define NRF905_RX_ADDRESS_IN_CR					5
#define NRF905_CMD_WC_MASK						0x0F
#define NRF905_CMD_WC(unWR_CFG_ByteIndex)		((unWR_CFG_ByteIndex) & NRF905_CMD_WC_MASK)	// Write Configuration register
#define NRF905_CMD_RC_MASK						0x0F
#define NRF905_CMD_RC(unRD_CFG_ByteIndex)		(((unRD_CFG_ByteIndex) & NRF905_CMD_RC_MASK) | 0x10)	// Read Configuration register
#define NRF905_CMD_WTP							0x20
#define NRF905_CMD_RTP							0x21
#define NRF905_CMD_WTA							0x22
#define NRF905_CMD_RTA							0x23
#define NRF905_CMD_RRP							0x24
#define NRF905_CMD_CC(unPwrChn)					((unPwrChn) | 0x1000)
#define CH_MSK_IN_CC_REG						0x01FF
#define NRF905_DR_IN_STATUS_REG(status)			((status) & (0x01 << 5))

#define HOPPING_MAX_CD_RETRY_NUM				100
#define HOPPING_MAX_RETRY_NUM					HOPPING_MAX_CD_RETRY_NUM
#define EXEC_TSK_MAX_CD_RETRY_NUM				HOPPING_MAX_CD_RETRY_NUM
#define CD_RETRY_DELAY_US						50
#define HOPPING_TX_RETRY_DELAY_US				2000

#define AFTER_SET_BURST_TX_MAX_DELAY_US			30000
//	#define AFTER_SET_BURST_RX_MAX_CD_DELAY_US		50000
#define AFTER_RX_MODE_MAX_DR_DELAY_US			80000	// Since there maybe interference in tha air, the CD may be set very soon
//	#define AFTER_AM_MAX_DR_DELAY_US				80000

#define NRF905_MAX_COMM_ERR_BEFORE_HOPPING		20
#define MAX_CONNECTION_PENDING 					8    /* Max connection requests */
#define PID_EMPTY								0
#define RECEIVE_BUFFER_LENGTH					256
#define ACK_TASK_INTERVAL_US					200000

typedef enum _nRF905Modes {
	NRF905_MODE_PWR_DOWN = 0,
	NRF905_MODE_STD_BY,
	NRF905_MODE_BURST_RX,
	NRF905_MODE_BURST_TX,
	NRF905_MODE_MAX
} nRF905Mode_t;

typedef struct _nRF905PinLevelInMode {
	int nPWR_UP_PIN;
	int nTRX_CE_PIN;
	int nTX_EN_PIN;
} nRF905PinLevelInMode_t;

// Pin status according to each nRF905 mode
static const nRF905PinLevelInMode_t unNRF905MODE_PIN_LEVEL[] = {
		{ LOW, LOW, LOW},
		{ HIGH, LOW, LOW },
		{ HIGH, HIGH, LOW },
		{ HIGH, HIGH, HIGH } };

typedef struct _nRF905Status {
	unsigned int unNRF905RecvFrameCNT;
	unsigned int unNRF905SendFrameCNT;
	unsigned int unNRF905HoppingCNT;
	unsigned int unNRF905TxAddr;
	unsigned int unNRF905RxAddr;
	unsigned short int unNRF905CHN_PWR;
}nRF905Status_t;

static nRF905Status_t tNRF905Status = {0, 0, 0, 0, 0};

// MSB of CH_NO will always be 0
static const unsigned char NRF905_CR_DEFAULT[] = { 0x4C, 0x0C, // F=(422.4+(0x6C<<1)/10)*1; No retransmission; +6db; NOT reduce receive power
		(NRF905_RX_ADDR_LEN << 4) | NRF905_TX_ADDR_LEN,	// 4 bytes RX & TX address;
		NRF905_RX_PAYLOAD_LEN, NRF905_TX_PAYLOAD_LEN, // 16 bytes RX & TX package length;
		0x00, 0x0C, 0x40, 0x08,	// RX address is the calculation result of CH_NO
		0x58 };	// 16MHz crystal; enable CRC; CRC16

static int nRF905SPI_CHN = 0;
static int nRF905PipeFd[2];
static unsigned short int* pRoamingTable;
static int nRoamingTableLen;
static unsigned char unNRF905Power;

static int regDR_Event(nRF905Mode_t tNRF905Mode);

// No set mode in low level APIs because if you set Standby mode
// then after write SPI you don't know what to change back
static int nRF905SPI_WR_CMD(unsigned char unCMD, unsigned char *pData, int nDataLen) {
	int nResult;
	unsigned char* pBuff;
	if (nDataLen > 0) {
		pBuff = malloc(nDataLen + 1);
		if (pBuff) {
			pBuff[0] = unCMD;
			memcpy(pBuff + 1, pData, nDataLen);
			nResult = wiringPiSPIDataRW(nRF905SPI_CHN, pBuff, nDataLen + 1);
			free(pBuff);
			return nResult;
		} else {
			return (-1);
		}
	} else {
		return (-1);
	}
}

static int readStatusReg(void) {
	int nResult;
	unsigned char unStatus;
	unStatus = NRF905_CMD_RC(1);
	nResult = wiringPiSPIDataRW(nRF905SPI_CHN, &unStatus, 1);
	if (0 == nResult) {
		return unStatus;
	} else {
		return (-1);
	}
}

static int readRxPayload(unsigned char* pBuff, int nBuffLen) {
	int nResult;
	unsigned char unReadBuff[33];
	if ((nBuffLen > 0) && (nBuffLen < sizeof(unReadBuff))) {
		unReadBuff[0] = NRF905_CMD_RTP;
		nResult = wiringPiSPIDataRW(nRF905SPI_CHN, unReadBuff, nBuffLen + 1);
		memcpy(pBuff, unReadBuff + 1, nBuffLen);
		return nResult;
	} else {
		return (-1);
	}
}

static int writeConfig(unsigned char unConfigAddr, const unsigned char* pBuff, int nBuffLen) {
	return nRF905SPI_WR_CMD(NRF905_CMD_WC(unConfigAddr), pBuff, nBuffLen);
}

static int writeTxAddr(unsigned int unTxAddr) {
	return nRF905SPI_WR_CMD(NRF905_CMD_WTA, (unsigned char*)(&unTxAddr), 4);
}

static int writeRxAddr(unsigned int unRxAddr) {
	return writeConfig(NRF905_RX_ADDRESS_IN_CR, (unsigned char*)(&unRxAddr), 4);
}

// TX and RX address are already configured during hopping
static int writeTxPayload(unsigned char* pBuff, int nBuffLen) {
	return writeConfig(NRF905_CMD_WTP, pBuff, nBuffLen);
}

static int writeFastConfig(unsigned short int unPA_PLL_CHN) {
	return wiringPiSPIDataRW(nRF905SPI_CHN, (unsigned char *)(&unPA_PLL_CHN), 2);
}

static int setNRF905Mode(nRF905Mode_t tNRF905Mode) {
	static nRF905Mode_t tNRF905ModeGlobal = NRF905_MODE_PWR_DOWN;

	if (tNRF905Mode >= NRF905_MODE_MAX){
		NRF905_LOG_ERR("nRF905 Mode error.");
		return (-1);
	}
	if (tNRF905Mode == tNRF905ModeGlobal){
		NRF905_LOG_INFO("nRF905 Mode not changed, no need to set pin.");
		return 0;
	}

	digitalWrite(NRF905_TX_EN_PIN, unNRF905MODE_PIN_LEVEL[tNRF905Mode].nTX_EN_PIN);
	digitalWrite(NRF905_TRX_CE_PIN, unNRF905MODE_PIN_LEVEL[tNRF905Mode].nTRX_CE_PIN);
	digitalWrite(NRF905_PWR_UP_PIN, unNRF905MODE_PIN_LEVEL[tNRF905Mode].nPWR_UP_PIN);
	tNRF905ModeGlobal = tNRF905Mode;

	return 0;
}

static int setChannelMonitorTimer(void) {
	struct itimerval tChannelMonitorTimer;  /* for setting itimer */
	tChannelMonitorTimer.it_value.tv_sec = 1;
	tChannelMonitorTimer.it_value.tv_usec = 0;
	tChannelMonitorTimer.it_interval.tv_sec = 1;
	tChannelMonitorTimer.it_interval.tv_usec = 0;
	return setitimer(ITIMER_REAL, &tChannelMonitorTimer, NULL);
}

static void switchNRF905ToRecv(void) {
	setNRF905Mode(NRF905_MODE_BURST_RX);
	regDR_Event(NRF905_MODE_BURST_RX);
}

static void readDataFromNRF905(void) {
	static unsigned char unReadBuff[32];
	static int nStatusReg;

	setNRF905Mode(NRF905_MODE_STD_BY);
	// make sure DR was set
	nStatusReg = readStatusReg();
	if ((nStatusReg >= 0) && (NRF905_DR_IN_STATUS_REG(nStatusReg) == 0)) {
		// Strange happens, do something?
	} else {
		// reset monitor timer since communication seems OK
		setChannelMonitorTimer();
		tNRF905Status.unNRF905RecvFrameCNT++;
		readRxPayload(unReadBuff, sizeof(unReadBuff));
		if (write(nRF905PipeFd[1], unReadBuff, sizeof(unReadBuff)) != sizeof(unReadBuff)) {
			NRF905_LOG_ERR("Write nRF905 pipe error");
		}
	}
	switchNRF905ToRecv();
}

static int regDR_Event(nRF905Mode_t tNRF905Mode) {
	if (NRF905_MODE_BURST_RX == tNRF905Mode) {
		wiringPiISR (NRF905_DR_PIN, INT_EDGE_RISING, &readDataFromNRF905) ;
	} else if (NRF905_MODE_BURST_TX == tNRF905Mode) {
		wiringPiISR (NRF905_DR_PIN, INT_EDGE_RISING, &switchNRF905ToRecv) ;
	}
	return 0;
}

static int nRF905CRInitial(int nRF905SPI_Fd) {
	return writeConfig(0, NRF905_CR_DEFAULT, sizeof(NRF905_CR_DEFAULT));
}

static unsigned int getTxAddrFromChnPwr(unsigned int unNRF905CHN_PWR) {
	return ((unNRF905CHN_PWR | (unNRF905CHN_PWR << 16)) & 0xA33D59AA);
}

static unsigned int getRxAddrFromChnPwr(unsigned short int unNRF905CHN_PWR) {
	return ((unNRF905CHN_PWR | (unNRF905CHN_PWR << 16)) & 0x5CA259AA);
}

#define GET_CHN_PWR_FAST_CONFIG(x, y) 		((x) | ((y) << 10))

static void roamNRF905(void) {
	static int nHoppingPoint = 0;
	setNRF905Mode(NRF905_MODE_STD_BY);
	tNRF905Status.unNRF905CHN_PWR = GET_CHN_PWR_FAST_CONFIG(pRoamingTable[nHoppingPoint], unNRF905Power);
	tNRF905Status.unNRF905TxAddr = getTxAddrFromChnPwr(tNRF905Status.unNRF905CHN_PWR);
	tNRF905Status.unNRF905RxAddr = getRxAddrFromChnPwr(tNRF905Status.unNRF905CHN_PWR);
	writeFastConfig(tNRF905Status.unNRF905CHN_PWR);
	writeTxAddr(tNRF905Status.unNRF905TxAddr);
	writeRxAddr(tNRF905Status.unNRF905RxAddr);
	(nHoppingPoint < (nRoamingTableLen - 1)) ? (nHoppingPoint++):(nHoppingPoint = 0);
	tNRF905Status.unNRF905HoppingCNT++;
	switchNRF905ToRecv();
}

int nRF905Initial(int nSPI_Channel, int nSPI_Speed, unsigned char unPower) {
	int nRF905SPI_Fd;
	wiringPiSetup();
	(void)piHiPri(10);

	unNRF905Power = unPower;
	pinMode(NRF905_TX_EN_PIN, OUTPUT);
	pinMode(NRF905_TRX_CE_PIN, OUTPUT);
	pinMode(NRF905_PWR_UP_PIN, OUTPUT);
	pinMode(NRF905_DR_PIN, INPUT);
	setNRF905Mode(NRF905_MODE_STD_BY);
	nRF905SPI_Fd = wiringPiSPISetup(nSPI_Channel, nSPI_Speed);
	if (nRF905SPI_Fd != 0) {
		NRF905_LOG_ERR("nRF905 SPI initial error.");
		return (-1);
	}
	usleep(3000);
	nRF905SPI_CHN = nSPI_Channel;
	nRF905CRInitial(nRF905SPI_Fd);

	return 0;
}

int nRF905StartListen(const unsigned short int* pHoppingTable, int nTableLen) {
	// generate pip
	if (nRF905PipeFd[0] != 0) {
		close(nRF905PipeFd[0]);
	}
	if (nRF905PipeFd[1] != 0) {
		close(nRF905PipeFd[1]);
	}
	if (pipe(nRF905PipeFd) != 0) {
		NRF905_LOG_ERR("nRF905 pipe initial error.");
		return (-1);
	}
	pRoamingTable = pHoppingTable;
	nRoamingTableLen = nTableLen;
	// Set nRF905 in RX mode
	setNRF905Mode(NRF905_MODE_BURST_RX);
	// register ISR to handle data receive when DR rise edge
	regDR_Event(NRF905_MODE_BURST_RX);

	// start timer to watch communication, if do RX during 1s, start hopping
	if (signal(SIGALRM, (void (*)(int)) roamNRF905) == SIG_ERR) {
		NRF905_LOG_ERR("Unable to catch SIGALRM");
		close(nRF905PipeFd[0]);
		close(nRF905PipeFd[1]);
		return (-1);
	}
	raise(SIGALRM);

	if (setChannelMonitorTimer() != 0) {
		NRF905_LOG_ERR("error calling setitimer()");
		close(nRF905PipeFd[0]);
		close(nRF905PipeFd[1]);
		return (-1);
	}

	return 0;
}

void setNRF905Power(unsigned char unPower) {
	unNRF905Power = unPower;
}

// Block operation until there is any data in the pipe which was written in Data ready ISR
int nRF905ReadFrame(unsigned char* pReadBuff, int nBuffLen) {
	return read(nRF905PipeFd[0], pReadBuff, nBuffLen);
}

int nRF905SendFrame(unsigned char* pReadBuff, int nBuffLen) {
	setNRF905Mode(NRF905_MODE_STD_BY);
	writeTxPayload(pReadBuff, nBuffLen);
	setNRF905Mode(NRF905_MODE_BURST_TX);
	regDR_Event(NRF905_MODE_BURST_TX);
	tNRF905Status.unNRF905SendFrameCNT++;
	return 0;
}

int nRF905StopListen(void) {
	setNRF905Mode(NRF905_MODE_STD_BY);
	close(nRF905PipeFd[0]);
	close(nRF905PipeFd[1]);
	return 0;
}



